/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.DAO.GheDao;
import com.raven.DAO.PhongDao;
import com.raven.model.ChiTietGhe;
import com.raven.model.Model_Ghe;
import com.raven.model.PhongChieu;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author Daokh
 */
public class Form_ChoNgoi extends javax.swing.JPanel {

    PhongDao daoPhong;
    GheDao daoGhe;
    List<PhongChieu> ListPhong = new ArrayList<>();
    List<ChiTietGhe> ListGhe = new ArrayList<>();

    /**
     * Creates new form Form_ChoNgoi
     */
    public Form_ChoNgoi() {
        initComponents();
        daoPhong = new PhongDao();
        daoGhe = new GheDao();
        ListPhong = daoPhong.Select();
        ListGhe = daoGhe.Select();
        ListPhong.stream().forEach(s -> {
            cboPhong.addItem(s.getTenPhong());
        });
//        SodoGhe();
    }
    List<ChiTietGhe> List;
    List<ChiTietGhe> List2;
    Color cl;

    public void SodoGhe() {

        List = ListGhe.stream().filter(s -> s.getMaPhong().equalsIgnoreCase(ListPhong.get(cboPhong.getSelectedIndex()).getMaPhong())).limit(96).collect(Collectors.toList());

        for (ChiTietGhe s : List) {

            if (Character.compare(s.getTenGhe().charAt(0), 'H') == 0) {
                cl = Color.PINK;
            } else {
                cl = Color.GREEN;
            }

            Model_Ghe ghe = new Model_Ghe(cl, s.getTenGhe());
            ghe.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {

                    if (e.getComponent().getBackground().equals(Color.YELLOW)) {
                        if (Character.compare(s.getTenGhe().charAt(0), 'H') == 0) {
                            e.getComponent().setBackground(Color.PINK);
                        } else {
                            e.getComponent().setBackground(Color.GREEN);
                        }
                    } else {
                        e.getComponent().setBackground(Color.YELLOW);
                    }
                }
            });

            Sodochongoi3.add(ghe);
        }

        if (cboPhong.getSelectedIndex() >= 5) {
            List2 = ListGhe.stream().filter(s -> s.getMaPhong().equalsIgnoreCase(ListPhong.get(cboPhong.getSelectedIndex()).getMaPhong())).skip(96).collect(Collectors.toList());
            for (ChiTietGhe s : List2) {
                if (Character.compare(s.getTenGhe().charAt(0), 'J') == 0) {
                    cl = Color.RED;
                }
                Model_Ghe ghe2 = new Model_Ghe(cl, s.getTenGhe());
                ghe2.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (e.getComponent().getBackground().equals(Color.YELLOW)) {
                            if (Character.compare(s.getTenGhe().charAt(0), 'H') == 0) {
                                e.getComponent().setBackground(Color.PINK);
                            } else if (Character.compare(s.getTenGhe().charAt(0), 'J') == 0) {
                                e.getComponent().setBackground(Color.RED);
                            } else {
                                e.getComponent().setBackground(Color.GREEN);
                            }
                        } else {
                            e.getComponent().setBackground(Color.YELLOW);
                        }
                    }
                });
                Sodochongoivip.add(ghe2);
            }
        }

        Sodochongoi3.repaint();
        Sodochongoi3.revalidate();
        Sodochongoivip.repaint();
        Sodochongoivip.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboPhong = new javax.swing.JComboBox<>();
        Sodochongoi3 = new javax.swing.JPanel();
        Sodochongoivip = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Tên Phòng");

        cboPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPhongItemStateChanged(evt);
            }
        });
        cboPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPhongMouseClicked(evt);
            }
        });

        Sodochongoi3.setBackground(new java.awt.Color(255, 255, 255));
        Sodochongoi3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sodochongoi3.setFocusCycleRoot(true);
        Sodochongoi3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sodochongoi3.setPreferredSize(new java.awt.Dimension(3, 3));
        Sodochongoi3.setLayout(new java.awt.GridLayout(8, 12, 1, 1));

        Sodochongoivip.setBackground(new java.awt.Color(255, 255, 255));
        Sodochongoivip.setPreferredSize(new java.awt.Dimension(3, 3));
        Sodochongoivip.setLayout(new java.awt.GridLayout(1, 14, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Sodochongoi3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Sodochongoivip, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sodochongoi3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sodochongoivip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhongMouseClicked
//        Sodochongoi3.removeAll();
//        SodoGhe();
    }//GEN-LAST:event_cboPhongMouseClicked

    private void cboPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPhongItemStateChanged
        // TODO add your handling code here:
        Sodochongoi3.removeAll();
        Sodochongoivip.removeAll();
        SodoGhe();

    }//GEN-LAST:event_cboPhongItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sodochongoi3;
    private javax.swing.JPanel Sodochongoivip;
    private javax.swing.JComboBox<String> cboPhong;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
